class-ssas
Vasyl-Dzumedzei/good-devs-icecream pull request #18
Opened 2021-07-18 12:46 UTC by NataliiaProtsanyk

Задала стилі footer.
це не кінечний результат.

2021-07-18 14:46 UTC, Vasyl-Dzumedzei commented on src/sass/layout/_footer.scss
> +@mixin font {
міксіни прописуються так:  @include font(16px, 1.313, 0em, 700, center);

2021-07-18 14:47 UTC, Vasyl-Dzumedzei commented on src/sass/layout/_footer.scss
> +.social-networks-wrapper {
порожній селектор

2021-07-18 14:47 UTC, Vasyl-Dzumedzei commented on src/sass/layout/_footer.scss
> +.social-networks__link {
порожній селектор

2021-07-18 14:47 UTC, Vasyl-Dzumedzei commented on src/sass/layout/_footer.scss
> +.address {
Порожній селектор

2021-07-18 14:57 UTC, Vasyl-Dzumedzei requested changes
Повиправляй міксіни, бо шрифти виглядають трохи дивно на локал-хості та повидаляй порожні селектори

2021-07-18 15:32 UTC, NataliiaProtsanyk commented on src/sass/layout/_footer.scss
> +@mixin font {
Я просто не дуже тоді зрозуміла, виправлю.

2021-07-18 15:32 UTC, NataliiaProtsanyk commented on src/sass/layout/_footer.scss
> +.social-networks-wrapper {
Ще не всі стилі задала всім селекторам.

2021-07-19 15:11 UTC, Vasyl-Dzumedzei approved these changes

2021-07-19 15:11 UTC, merged